require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  TargetRubyVersion: 2.7.8
  NewCops: enable

Style/Documentation:
  Enabled: false

Lint/MissingSuper:
  Exclude:
    - 'app/services/**/*'